name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  # Adapted from: https://github.com/pypa/gh-action-pypi-publish#usage
  pypi-publish:
    name: Lint, Typecheck, Release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/plover-steno-engine-hooks-logger/
    permissions:
      id-token: write
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Lint, Type Checking Dependencies
        # NOTE: Due to issues with importing `plover_build_utils` in setup.py,
        # it is not possible to run `python -m pip install ".[test]"` here.
        run: python -m pip install mypy pylint

      - name: Run Linter
        run: pylint src

      - name: Run Type Checker
        run: mypy src

      - name: Install Build
        # NOTE: Install of plover explicitly needed in order to run setup.py,
        # which has a reference to `plover_build_tools`
        run: python -m pip install --upgrade "plover >= 4.0.0rc2" build wheel

      - name: Build
        # NOTE: Disabling build isolation (--no-isolation) would seem to enable
        # the build system to see `plover_build_utils`.
        run: python -m build --no-isolation

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs:
      - pypi-publish
    if: always() && needs.pypi-publish.result == 'success'
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$TAG" \
            --generate-notes
