name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Lint, Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Lint, Type Checking Dependencies
        run: python -m pip install mypy pylint

      - name: Run Linter
        run: pylint plover_steno_engine_hooks_logger

      - name: Run Type Checker
        run: mypy plover_steno_engine_hooks_logger

  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
        run: |
          gh release create "$TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$TAG" \
            --generate-notes
